### PR TITLE
feat: implement overlap method for event positioning

### PR DESCRIPTION
**Pull request by MinhOmega**
- feat: implement overlap method for event positioning that mentioned in #69

### CODE REVIEW

**Comment by howljs** [comment]
@MinhOmega
Thank you for your pull request, I will review it soon.

**Comment by howljs** [comment]
The display doesn’t seem quite right; I will consider another, better solution.

simulator_screenshot_4BA85D84-C8EE-4AC4-A529-D743674BFC17

**Comment by MinhOmega** [comment]
That sounds good! Please ping me if there's anything I can do to improve the event display further.

**Comment by howljs** [comment]
Updated in this PR: https://github.com/howljs/react-native-calendar-kit/pull/112

**Pull request closed without merging**
