### PR TITLE
fix: dayjs utcOffset is incorrect when handling dst

### PR DESCRIPTION
**Pull request by callaars**
@howljs this takes the extra offset off when DST is being applied.

### CODE REVIEW

**Comment by howljs** [comment]
@callaars I've changed the system time zone to Sydney but it seems to be wrong, Asia/Tokyo if it's right it should be 00:25

Screenshot 2023-01-13 at 02 25 57

Screenshot 2023-01-13 at 02 25 33

**Comment by howljs** [comment]
I'm still not clear about DST. I'll find out 😅

**Comment by howljs** [comment]
Sorry, in my country people don't use "Daylight Saving Time," so I don't understand this. You can confirm to me that it is working properly. If you are in Sydney, the time in Japan is from 00:00 will be increased to 01:00

Screenshot 2023-01-13 at 00 41 54

**Comment by callaars** [comment]
Ok, let me check some other cases because this is really hard. So the problem essentially is that `dayjs` adds extra offset to the timezone. So for example the UTC offset of `Australia/Sydney` is 600, but with dayjs it is 660, which is incorrect and adds the DST. 

Let me have a look and don't worry about it for now, I'll find a solution here.

**Comment by callaars** [comment]
ok so yeah you are right, it uses the incorrect time at that point, let me handle that.

**Comment by howljs** [comment]
Can you share me an example video on this issue? And what are you expecting?

**Comment by howljs** [comment]
@callaars Please help me check this PR
https://github.com/howljs/react-native-calendar-kit/pull/29

**Comment by SwikarBhattarai** [comment]
@howljs please have a look at this, it looks like this works well with the different timezones and daylight saving.

**Comment by callaars** [comment]
@howljs I've updated it according to the newest version on `main`.

**Comment by howljs** [comment]
@callaars Thanks for your PR, I will release the new version soon

**Comment by callaars** [comment]
You're a star @howljs !

**Comment by howljs** [comment]
@callaars  Sorry for the delay. I'm in the process of writing another calendar version, so I don't update too much in this version

https://user-images.githubusercontent.com/33460888/223484472-5f77066e-c8fd-4504-867c-c08a2aafaa76.mp4

**Comment by callaars** [comment]
Why another calendar version, are you not happy with this one?

**Comment by howljs** [comment]
I want it to be even more stable. I'm still reviewing, maybe after completion, all the code will be included in this repository

**Comment by callaars** [comment]
If you need help, let me know!

**Pull request merged**
